name: DevOps Dashboard CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      #################################################
      # Backend
      #################################################

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      #################################################
      # Frontend
      #################################################

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build React
        working-directory: frontend
        run: npm run build

      #################################################
      # Deploy to Local Project
      #################################################

      - name: Copy React Build
        shell: powershell
        run: |
          $project = "C:\Projects\DevOpsDashboard"

          Remove-Item "$project\backend\dist" -Recurse -Force -ErrorAction SilentlyContinue

          New-Item -ItemType Directory -Force -Path "$project\backend\dist"

          Copy-Item frontend\dist\* "$project\backend\dist" -Recurse -Force

      - name: Restart Backend
        shell: powershell
        run: |
          cd C:\Projects\DevOpsDashboard\backend
          pm2 restart devops-backend

      - name: Deployment Finished
        run: echo "Deployment completed successfully!"